apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  debug: true
  namespace: trident
  silence_autosupport: true
