apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: hco-operatorhub
spec:
  source: kubevirt-hyperconverged
  sourceNamespace: kubevirt-hyperconverged
  name: community-kubevirt-hyperconverged
  startingCSV: kubevirt-hyperconverged-operator.v1.5.0
  channel: "1.5.0"
