apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fedora-dvtest
  namespace: openshift-gitops
spec:
  destination:
    namespace:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: vm-and-dvs
    repoURL: https://github.com/cwilkers/kubevirt-gitops
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=false
